In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import re

In [2]:
data = pd.read_csv('../Datasets/csv/patients.csv')

In [3]:
data

,86ea3680-c314-2cad-79d7-ef5db46ac53d,2008-09-22,Unnamed: 2,999-73-5678,S99988450,Unnamed: 5,Unnamed: 6,Ezra452,Frankie174,Bogan287,...,Groton,Massachusetts,Middlesex County,25017,01450,42.63588994161408,-71.55617201508895,43706.10,26495.11,35051
0,f79404d1-856e-6483-efb5-c59ae407cc4f,2007-11-08,NaN,999-83-9576,S99966920,NaN,NaN,Ela754,NaN,Roberts511,...,Boston,Massachusetts,Suffolk County,25025.0,2111,42.377880,-71.150968,35750.81,51349.81,194973
1,ff7ac362-cb56-650d-5cd4-1a7bf93bfa53,2002-03-11,NaN,999-44-7496,S99925040,X28226638X,Mr.,Von197,NaN,Sauer652,...,Leicester,Massachusetts,Worcester County,NaN,0,42.198972,-71.914731,5170.93,67204.05,7737
2,64b17845-be57-2777-232c-2b5298e28867,2004-10-02,NaN,999-30-1903,S99936224,X68395742X,Ms.,Johnetta529,Majorie11,Lueilwitz711,...,New Bedford,Massachusetts,Bristol County,25005.0,2747,41.614289,-70.923399,51745.02,5416.44,144791
3,797457c1-944e-412a-7895-765be4761a76,2003-07-16,NaN,999-91-3408,S99995566,X25480357X,Ms.,Shaquita282,Jane262,Gutkowski940,...,Lowell,Massachusetts,Middlesex County,25017.0,1852,42.672504,-71.381567,110478.37,254262.07,70833
4,cdcf4a7d-82ea-6251-a2e6-5c81df887fb2,1990-05-11,NaN,999-89-7517,S99944746,X53056401X,Mr.,Samuel331,NaN,Pantoja215,...,Boston,Massachusetts,Suffolk County,25025.0,2108,42.323205,-71.081278,95486.27,5108.79,188422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13847,ea432e6e-cd08-7aa7-aec4-f84e58de9438,1916-02-25,NaN,999-93-3698,S99910239,X24332068X,Mr.,Francisco472,NaN,Raya927,...,Dracut,Massachusetts,Middlesex County,NaN,0,42.703358,-71.258314,252214.29,160077.58,52480
13848,13a22b23-4a9a-3c81-a49d-1b5b5d860a22,1938-12-24,NaN,999-51-2412,S99939991,X62290486X,Mrs.,Marlana402,Cherrie404,Bayer639,...,Randolph,Massachusetts,Norfolk County,25021.0,2368,42.134344,-71.033445,827858.87,308637.74,60425
13849,94624af1-2352-16ba-dabe-9f264456f625,1930-10-12,NaN,999-33-5684,S99994120,X51163908X,Mrs.,Sharonda198,Yuette836,Pollich983,...,Gloucester,Massachusetts,Essex County,25009.0,1930,42.587794,-70.705418,1140406.03,1575970.45,66847
13850,d3dedcfd-08af-6326-31eb-6d5d7f28f984,1960-05-02,2011-07-29,999-61-6192,S99969708,X63685098X,Mr.,Owen89,NaN,Jones311,...,Arlington,Massachusetts,Middlesex County,25017.0,2476,42.394910,-71.189216,213002.08,1254434.44,153605
13851,fb67c2a7-f8a7-31e2-e52f-eca11ed8ecd3,1960-05-02,NaN,999-98-2329,S99994277,X8150599X,Mr.,Dante562,Sterling124,Hirthe744,...,Arlington,Massachusetts,Middlesex County,25017.0,2476,42.399125,-71.177111,219891.17,97924.18,153605

In [4]:
data.columns

Index(['86ea3680-c314-2cad-79d7-ef5db46ac53d', '2008-09-22', 'Unnamed: 2',
       '999-73-5678', 'S99988450', 'Unnamed: 5', 'Unnamed: 6', 'Ezra452',
       'Frankie174', 'Bogan287', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'white', 'nonhispanic', 'M', 'Pittsfield  Massachusetts  US',
       '802 Koss Gate Apt 43', 'Groton', 'Massachusetts', 'Middlesex County',
       '25017', '01450', '42.63588994161408', '-71.55617201508895', '43706.10',
       '26495.11', '35051'],
      dtype='object')

In [5]:
data.iloc[:, [9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]]

,Bogan287,Unnamed: 10,Unnamed: 11,Unnamed: 12,white,nonhispanic,M,Pittsfield Massachusetts US,802 Koss Gate Apt 43,Groton,Massachusetts,Middlesex County,25017
0,Roberts511,NaN,NaN,NaN,black,nonhispanic,F,Easthampton Massachusetts US,146 Vandervort Mill,Boston,Massachusetts,Suffolk County,25025.0
1,Sauer652,NaN,NaN,NaN,white,nonhispanic,M,Weymouth Massachusetts US,996 Hettinger Rest,Leicester,Massachusetts,Worcester County,NaN
2,Lueilwitz711,NaN,NaN,NaN,black,nonhispanic,F,Groveland Massachusetts US,156 Hahn Vale Apt 13,New Bedford,Massachusetts,Bristol County,25005.0
3,Gutkowski940,NaN,NaN,NaN,white,nonhispanic,F,Boston Massachusetts US,267 Ritchie Estate Apt 2,Lowell,Massachusetts,Middlesex County,25017.0
4,Pantoja215,NaN,NaN,M,white,hispanic,M,Bogota Bogota CO,974 Heller Harbor Suite 33,Boston,Massachusetts,Suffolk County,25025.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13847,Raya927,NaN,NaN,M,white,hispanic,M,Caracas Capital District VE,633 Feest Trailer Suite 76,Dracut,Massachusetts,Middlesex County,NaN
13848,Bayer639,NaN,Bauch723,M,white,nonhispanic,F,New Bedford Massachusetts US,330 Feest Ferry Suite 14,Randolph,Massachusetts,Norfolk County,25021.0
13849,Pollich983,NaN,Russel238,M,white,nonhispanic,F,North Attleborough Massachusetts US,936 Treutel Tunnel Apt 65,Gloucester,Massachusetts,Essex County,25009.0
13850,Jones311,NaN,NaN,M,black,nonhispanic,M,Norwood Massachusetts US,586 Marquardt Alley Apt 1,Arlington,Massachusetts,Middlesex County,25017.0
13851,Hirthe744,NaN,NaN,M,black,nonhispanic,M,Weston Massachusetts US,195 Auer Crossroad,Arlington,Massachusetts,Middlesex County,25017.0

# Renaming the columns and dropping irrelevenat columns

In [6]:
data.columns

Index(['86ea3680-c314-2cad-79d7-ef5db46ac53d', '2008-09-22', 'Unnamed: 2',
       '999-73-5678', 'S99988450', 'Unnamed: 5', 'Unnamed: 6', 'Ezra452',
       'Frankie174', 'Bogan287', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12',
       'white', 'nonhispanic', 'M', 'Pittsfield  Massachusetts  US',
       '802 Koss Gate Apt 43', 'Groton', 'Massachusetts', 'Middlesex County',
       '25017', '01450', '42.63588994161408', '-71.55617201508895', '43706.10',
       '26495.11', '35051'],
      dtype='object')

In [7]:
len(data.columns)

28

In [8]:
data.drop(columns=["Unnamed: 12", "Pittsfield  Massachusetts  US", 'Middlesex County', '25017'], inplace=True)

In [9]:
new_cols_list=["uuid", "birth_date", "death_date", "social_security_number", "driver's_license_number", "passport_number", "salutation", "first_name",
                "middle_name", "last_name", "marital_status", "maiden_family", "skin_color", "hispanic", "gender", "address", "city", "state", "postal_code","latitude","longitude",
                "family_income"]    

old_cols = data.columns

for old_col, new_col in zip(old_cols, new_cols_list):
    data = data.rename(columns={old_col: new_col})

In [10]:
data

,uuid,birth_date,death_date,social_security_number,driver's_license_number,passport_number,salutation,first_name,middle_name,last_name,...,gender,address,city,state,postal_code,latitude,longitude,family_income,26495.11,35051
0,f79404d1-856e-6483-efb5-c59ae407cc4f,2007-11-08,NaN,999-83-9576,S99966920,NaN,NaN,Ela754,NaN,Roberts511,...,F,146 Vandervort Mill,Boston,Massachusetts,2111,42.377880,-71.150968,35750.81,51349.81,194973
1,ff7ac362-cb56-650d-5cd4-1a7bf93bfa53,2002-03-11,NaN,999-44-7496,S99925040,X28226638X,Mr.,Von197,NaN,Sauer652,...,M,996 Hettinger Rest,Leicester,Massachusetts,0,42.198972,-71.914731,5170.93,67204.05,7737
2,64b17845-be57-2777-232c-2b5298e28867,2004-10-02,NaN,999-30-1903,S99936224,X68395742X,Ms.,Johnetta529,Majorie11,Lueilwitz711,...,F,156 Hahn Vale Apt 13,New Bedford,Massachusetts,2747,41.614289,-70.923399,51745.02,5416.44,144791
3,797457c1-944e-412a-7895-765be4761a76,2003-07-16,NaN,999-91-3408,S99995566,X25480357X,Ms.,Shaquita282,Jane262,Gutkowski940,...,F,267 Ritchie Estate Apt 2,Lowell,Massachusetts,1852,42.672504,-71.381567,110478.37,254262.07,70833
4,cdcf4a7d-82ea-6251-a2e6-5c81df887fb2,1990-05-11,NaN,999-89-7517,S99944746,X53056401X,Mr.,Samuel331,NaN,Pantoja215,...,M,974 Heller Harbor Suite 33,Boston,Massachusetts,2108,42.323205,-71.081278,95486.27,5108.79,188422
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13847,ea432e6e-cd08-7aa7-aec4-f84e58de9438,1916-02-25,NaN,999-93-3698,S99910239,X24332068X,Mr.,Francisco472,NaN,Raya927,...,M,633 Feest Trailer Suite 76,Dracut,Massachusetts,0,42.703358,-71.258314,252214.29,160077.58,52480
13848,13a22b23-4a9a-3c81-a49d-1b5b5d860a22,1938-12-24,NaN,999-51-2412,S99939991,X62290486X,Mrs.,Marlana402,Cherrie404,Bayer639,...,F,330 Feest Ferry Suite 14,Randolph,Massachusetts,2368,42.134344,-71.033445,827858.87,308637.74,60425
13849,94624af1-2352-16ba-dabe-9f264456f625,1930-10-12,NaN,999-33-5684,S99994120,X51163908X,Mrs.,Sharonda198,Yuette836,Pollich983,...,F,936 Treutel Tunnel Apt 65,Gloucester,Massachusetts,1930,42.587794,-70.705418,1140406.03,1575970.45,66847
13850,d3dedcfd-08af-6326-31eb-6d5d7f28f984,1960-05-02,2011-07-29,999-61-6192,S99969708,X63685098X,Mr.,Owen89,NaN,Jones311,...,M,586 Marquardt Alley Apt 1,Arlington,Massachusetts,2476,42.394910,-71.189216,213002.08,1254434.44,153605
13851,fb67c2a7-f8a7-31e2-e52f-eca11ed8ecd3,1960-05-02,NaN,999-98-2329,S99994277,X8150599X,Mr.,Dante562,Sterling124,Hirthe744,...,M,195 Auer Crossroad,Arlington,Massachusetts,2476,42.399125,-71.177111,219891.17,97924.18,153605

In [11]:
pattern = r'^[-]?[0-9]+.[0-9]+$'

dropped_cols = [col for col in data.columns if re.match(pattern, col)]

data.drop(columns = dropped_cols, inplace=True)
data.columns

Index(['uuid', 'birth_date', 'death_date', 'social_security_number',
       'driver's_license_number', 'passport_number', 'salutation',
       'first_name', 'middle_name', 'last_name', 'marital_status',
       'maiden_family', 'skin_color', 'hispanic', 'gender', 'address', 'city',
       'state', 'postal_code', 'latitude', 'longitude', 'family_income'],
      dtype='object')

In [12]:
data

,uuid,birth_date,death_date,social_security_number,driver's_license_number,passport_number,salutation,first_name,middle_name,last_name,...,skin_color,hispanic,gender,address,city,state,postal_code,latitude,longitude,family_income
0,f79404d1-856e-6483-efb5-c59ae407cc4f,2007-11-08,NaN,999-83-9576,S99966920,NaN,NaN,Ela754,NaN,Roberts511,...,black,nonhispanic,F,146 Vandervort Mill,Boston,Massachusetts,2111,42.377880,-71.150968,35750.81
1,ff7ac362-cb56-650d-5cd4-1a7bf93bfa53,2002-03-11,NaN,999-44-7496,S99925040,X28226638X,Mr.,Von197,NaN,Sauer652,...,white,nonhispanic,M,996 Hettinger Rest,Leicester,Massachusetts,0,42.198972,-71.914731,5170.93
2,64b17845-be57-2777-232c-2b5298e28867,2004-10-02,NaN,999-30-1903,S99936224,X68395742X,Ms.,Johnetta529,Majorie11,Lueilwitz711,...,black,nonhispanic,F,156 Hahn Vale Apt 13,New Bedford,Massachusetts,2747,41.614289,-70.923399,51745.02
3,797457c1-944e-412a-7895-765be4761a76,2003-07-16,NaN,999-91-3408,S99995566,X25480357X,Ms.,Shaquita282,Jane262,Gutkowski940,...,white,nonhispanic,F,267 Ritchie Estate Apt 2,Lowell,Massachusetts,1852,42.672504,-71.381567,110478.37
4,cdcf4a7d-82ea-6251-a2e6-5c81df887fb2,1990-05-11,NaN,999-89-7517,S99944746,X53056401X,Mr.,Samuel331,NaN,Pantoja215,...,white,hispanic,M,974 Heller Harbor Suite 33,Boston,Massachusetts,2108,42.323205,-71.081278,95486.27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13847,ea432e6e-cd08-7aa7-aec4-f84e58de9438,1916-02-25,NaN,999-93-3698,S99910239,X24332068X,Mr.,Francisco472,NaN,Raya927,...,white,hispanic,M,633 Feest Trailer Suite 76,Dracut,Massachusetts,0,42.703358,-71.258314,252214.29
13848,13a22b23-4a9a-3c81-a49d-1b5b5d860a22,1938-12-24,NaN,999-51-2412,S99939991,X62290486X,Mrs.,Marlana402,Cherrie404,Bayer639,...,white,nonhispanic,F,330 Feest Ferry Suite 14,Randolph,Massachusetts,2368,42.134344,-71.033445,827858.87
13849,94624af1-2352-16ba-dabe-9f264456f625,1930-10-12,NaN,999-33-5684,S99994120,X51163908X,Mrs.,Sharonda198,Yuette836,Pollich983,...,white,nonhispanic,F,936 Treutel Tunnel Apt 65,Gloucester,Massachusetts,1930,42.587794,-70.705418,1140406.03
13850,d3dedcfd-08af-6326-31eb-6d5d7f28f984,1960-05-02,2011-07-29,999-61-6192,S99969708,X63685098X,Mr.,Owen89,NaN,Jones311,...,black,nonhispanic,M,586 Marquardt Alley Apt 1,Arlington,Massachusetts,2476,42.394910,-71.189216,213002.08
13851,fb67c2a7-f8a7-31e2-e52f-eca11ed8ecd3,1960-05-02,NaN,999-98-2329,S99994277,X8150599X,Mr.,Dante562,Sterling124,Hirthe744,...,black,nonhispanic,M,195 Auer Crossroad,Arlington,Massachusetts,2476,42.399125,-71.177111,219891.17

In [16]:
data[["first_name", "marital_status"]].tail(10)

         first_name marital_status
13842       Lady554            NaN
13843      Javier97            NaN
13844    Obdulia648            NaN
13845     Jacobo456            NaN
13846       Vita624            NaN
13847  Francisco472            NaN
13848    Marlana402            NaN
13849   Sharonda198            NaN
13850        Owen89            NaN
13851      Dante562            NaN

In [17]:
data["skin_color"].value_counts()

skin_color
white       11321
black        1208
asian         893
hawaiian      182
other         181
native         67
Name: count, dtype: int64

In [18]:
data['marital_status'].value_counts()

marital_status
MD     51
PhD    48
JD     46
Name: count, dtype: int64

In [15]:
data.columns

Index(['uuid', 'birth_date', 'death_date', 'social_security_number',
       'driver's_license_number', 'passport_number', 'salutation',
       'first_name', 'middle_name', 'last_name', 'marital_status',
       'skin_color', 'hispanic', 'gender', 'address', 'city', 'state',
       'postal_code', 'latitude', 'longitude', 'family_income'],
      dtype='object')

In [16]:
data[data['uuid'] == "7c74cbbf-caf7-3923-add7-b2f9343df1b7"]

,uuid,birth_date,death_date,social_security_number,driver's_license_number,passport_number,salutation,first_name,middle_name,last_name,...,skin_color,hispanic,gender,address,city,state,postal_code,latitude,longitude,family_income
6,7c74cbbf-caf7-3923-add7-b2f9343df1b7,1995-11-20,NaN,999-24-6710,S99912306,X17506108X,Ms.,Janyce124,NaN,Armstrong51,...,white,nonhispanic,F,662 Cummings Mall,Boston,Massachusetts,2151,42.32618,-71.05417,152678

In [18]:
data2 = pd.read_csv('../Datasets/conditions.csv')
data2

,2025-06-13,2025-06-13.1,85e5acb8-9ff4-597d-94d2-19704ee2665c,85e5acb8-9ff4-597d-913a-744ae0361d31,http://snomed.info/sct,314529007,Medication review due (situation)
0,2025-07-18,NaN,85e5acb8-9ff4-597d-94d2-19704ee2665c,85e5acb8-9ff4-597d-dc75-6bfcc84cc3d8,http://snomed.info/sct,314529007,Medication review due (situation)
1,2020-04-12,2020-07-19,44e5aa82-e51c-af3f-c80a-055fb5f73863,44e5aa82-e51c-af3f-d133-a6b2e66b0cf4,http://snomed.info/sct,314529007,Medication review due (situation)
2,2020-09-20,2020-09-20,44e5aa82-e51c-af3f-c80a-055fb5f73863,44e5aa82-e51c-af3f-4e40-3890bb8d5f16,http://snomed.info/sct,314529007,Medication review due (situation)
3,2015-07-07,2017-01-10,9ec76493-d732-13e5-5cd3-7fa0d2e80ace,9ec76493-d732-13e5-fe1c-1e0ee7ba3fcf,http://snomed.info/sct,314529007,Medication review due (situation)
4,2020-12-20,2021-03-21,44e5aa82-e51c-af3f-c80a-055fb5f73863,44e5aa82-e51c-af3f-17c3-e5cf81970c80,http://snomed.info/sct,314529007,Medication review due (situation)
...,...,...,...,...,...,...,...
39155,2024-12-17,2025-05-14,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-6f01-fdaac963d994,http://snomed.info/sct,283545005,Gunshot wound (disorder)
39156,2024-12-17,2025-05-14,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-6f01-fdaac963d994,http://snomed.info/sct,262574004,Bullet wound (disorder)
39157,2025-06-10,NaN,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-0071-ac4782becee7,http://snomed.info/sct,73595000,Stress (finding)
39158,2025-06-10,NaN,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-0071-ac4782becee7,http://snomed.info/sct,424393004,Reports of violence in the environment (finding)
39159,2025-06-10,NaN,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-0071-ac4782becee7,http://snomed.info/sct,80583007,Severe anxiety (panic) (finding)

In [19]:
data2[data2['85e5acb8-9ff4-597d-94d2-19704ee2665c'] == "daaf82d6-2984-5da6-ac3c-e2df631879eb"]

,2025-06-13,2025-06-13.1,85e5acb8-9ff4-597d-94d2-19704ee2665c,85e5acb8-9ff4-597d-913a-744ae0361d31,http://snomed.info/sct,314529007,Medication review due (situation)
18,1996-12-15,NaN,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-feda-d53a74671216,http://snomed.info/sct,224299000,Received higher education (finding)
19,1997-12-21,2016-01-10,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-b645-69fd2cafb6dc,http://snomed.info/sct,314529007,Medication review due (situation)
20,2000-12-24,NaN,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-e794-5c6abb43db9c,http://snomed.info/sct,162864005,Body mass index 30+ - obesity (finding)
21,2006-12-31,2018-10-28,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-8568-94e7aee63317,http://snomed.info/sct,160903007,Full-time employment (finding)
22,2010-01-03,NaN,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-583b-907685df5372,http://snomed.info/sct,714628002,Prediabetes (finding)
23,2010-01-03,2020-11-01,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-583b-907685df5372,http://snomed.info/sct,73595000,Stress (finding)
24,2013-11-15,NaN,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-f25b-5293b25de4cb,http://snomed.info/sct,40055000,Chronic sinusitis (disorder)
25,2014-08-27,NaN,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-4dd9-948f18bd7899,http://snomed.info/sct,267020005,History of tubal ligation (situation)
26,2016-01-10,2018-10-28,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-9a6c-0cfa8351bd06,http://snomed.info/sct,424393004,Reports of violence in the environment (finding)
27,2018-10-28,2021-12-19,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-3ccb-bdd306d5a774,http://snomed.info/sct,314529007,Medication review due (situation)
28,2018-10-28,2020-11-01,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-3ccb-bdd306d5a774,http://snomed.info/sct,160904001,Part-time employment (finding)
29,2018-11-11,2018-11-11,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-4c29-a64a844cdf20,http://snomed.info/sct,427898007,Infection of tooth (disorder)
30,2018-11-11,2018-11-11,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-4c29-a64a844cdf20,http://snomed.info/sct,109570002,Primary dental caries (disorder)
31,2018-11-16,2018-11-16,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-9dad-5015bddc75cd,http://snomed.info/sct,61804006,Alveolitis of jaw (disorder)
32,2020-07-05,2020-07-18,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-9d31-acc359b221d4,http://snomed.info/sct,195662009,Acute viral pharyngitis (disorder)
33,2020-11-01,2021-11-14,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-35db-f8418c445da7,http://snomed.info/sct,160903007,Full-time employment (finding)
34,2020-11-01,2021-11-14,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-35db-f8418c445da7,http://snomed.info/sct,422650009,Social isolation (finding)
35,2020-12-08,2020-12-08,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-35db-f8418c445da7,http://snomed.info/sct,840544004,Suspected disease caused by Severe acute respi...
36,2020-12-08,NaN,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-e23f-7bfa048ebd28,http://snomed.info/sct,267102003,Sore throat (finding)
37,2020-12-08,NaN,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-e23f-7bfa048ebd28,http://snomed.info/sct,84229001,Fatigue (finding)
38,2020-12-08,NaN,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-e23f-7bfa048ebd28,http://snomed.info/sct,386661006,Fever (finding)
39,2021-09-09,2021-12-19,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-3a4a-9fae01f9a3a5,http://snomed.info/sct,75498004,Acute bacterial sinusitis (disorder)
40,2021-11-14,2021-11-28,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-93a6-e47a63e874bb,http://snomed.info/sct,160904001,Part-time employment (finding)
41,2021-11-14,2021-12-05,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-93a6-e47a63e874bb,http://snomed.info/sct,66383009,Gingivitis (disorder)
42,2021-11-28,2021-12-19,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-1315-5543686c020a,http://snomed.info/sct,741062008,Not in labor force (finding)
43,2021-12-05,2021-12-05,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-ecd4-287d924eef49,http://snomed.info/sct,18718003,Gingival disease (disorder)
44,2021-12-19,2022-11-06,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-4730-395e48e299d4,http://snomed.info/sct,160904001,Part-time employment (finding)
45,2022-11-06,2022-11-06,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-c827-ec0af7b72589,http://snomed.info/sct,314529007,Medication review due (situation)
46,2022-11-06,2024-11-10,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-c827-ec0af7b72589,http://snomed.info/sct,741062008,Not in labor force (finding)
47,2022-11-06,2024-11-10,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-c827-ec0af7b72589,http://snomed.info/sct,73595000,Stress (finding)
48,2024-11-10,NaN,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-3290-93819f0cc579,http://snomed.info/sct,314529007,Medication review due (situation)
49,2024-11-10,NaN,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-3290-93819f0cc579,http://snomed.info/sct,160903007,Full-time employment (finding)

In [20]:
data2 = data2.rename(columns={

    "2025-06-13": "event_start",
    "2025-06-13.1": "event_end",
    "85e5acb8-9ff4-597d-94d2-19704ee2665c": "uuid",
    "314529007": "event_code",
    "Medication review due (situation)": "event",
    "85e5acb8-9ff4-597d-913a-744ae0361d31": "record_id"
    
    
}).drop(columns=['http://snomed.info/sct'])

In [21]:
data2['event_end'] = data2['event_end'].fillna(value="Undergoing")
data2

,event_start,event_end,uuid,record_id,event_code,event
0,2025-07-18,Undergoing,85e5acb8-9ff4-597d-94d2-19704ee2665c,85e5acb8-9ff4-597d-dc75-6bfcc84cc3d8,314529007,Medication review due (situation)
1,2020-04-12,2020-07-19,44e5aa82-e51c-af3f-c80a-055fb5f73863,44e5aa82-e51c-af3f-d133-a6b2e66b0cf4,314529007,Medication review due (situation)
2,2020-09-20,2020-09-20,44e5aa82-e51c-af3f-c80a-055fb5f73863,44e5aa82-e51c-af3f-4e40-3890bb8d5f16,314529007,Medication review due (situation)
3,2015-07-07,2017-01-10,9ec76493-d732-13e5-5cd3-7fa0d2e80ace,9ec76493-d732-13e5-fe1c-1e0ee7ba3fcf,314529007,Medication review due (situation)
4,2020-12-20,2021-03-21,44e5aa82-e51c-af3f-c80a-055fb5f73863,44e5aa82-e51c-af3f-17c3-e5cf81970c80,314529007,Medication review due (situation)
...,...,...,...,...,...,...
39155,2024-12-17,2025-05-14,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-6f01-fdaac963d994,283545005,Gunshot wound (disorder)
39156,2024-12-17,2025-05-14,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-6f01-fdaac963d994,262574004,Bullet wound (disorder)
39157,2025-06-10,Undergoing,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-0071-ac4782becee7,73595000,Stress (finding)
39158,2025-06-10,Undergoing,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-0071-ac4782becee7,424393004,Reports of violence in the environment (finding)
39159,2025-06-10,Undergoing,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-0071-ac4782becee7,80583007,Severe anxiety (panic) (finding)

In [22]:
data3 = pd.read_csv('../Datasets/allergies.csv')

In [23]:
data3

,1996-10-03,Unnamed: 1,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,609328004,SNOMED-CT,Allergic disposition (finding),allergy,environment,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,1996-10-03,NaN,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,111088007,SNOMED-CT,Latex (substance),allergy,environment,247472004.0,Wheal (finding),MILD,NaN,NaN,NaN
1,1996-10-03,NaN,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,84489001,SNOMED-CT,Mold (organism),allergy,environment,21626009.0,Cutaneous hypersensitivity (disorder),MILD,76067001.0,Sneezing (finding),MILD
2,1996-10-03,NaN,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,260147004,SNOMED-CT,House dust mite (organism),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
3,1996-10-03,NaN,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,264287008,SNOMED-CT,Animal dander (substance),allergy,environment,878820003.0,Rhinoconjunctivitis (disorder),MODERATE,49727002.0,Cough (finding),MODERATE
4,1996-10-03,NaN,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,3718001,SNOMED-CT,Cow's milk (substance),allergy,food,247472004.0,Wheal (finding),MILD,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,1968-06-18,NaN,1f8dcaff-1cf9-fac5-a278-8ade5dc2dbf5,1f8dcaff-1cf9-fac5-838a-be81c45c0a2d,256277009,SNOMED-CT,Grass pollen (substance),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
936,1968-06-18,NaN,1f8dcaff-1cf9-fac5-a278-8ade5dc2dbf5,1f8dcaff-1cf9-fac5-838a-be81c45c0a2d,3718001,SNOMED-CT,Cow's milk (substance),allergy,food,247472004.0,Wheal (finding),MILD,NaN,NaN,NaN
937,1968-06-18,NaN,1f8dcaff-1cf9-fac5-a278-8ade5dc2dbf5,1f8dcaff-1cf9-fac5-838a-be81c45c0a2d,735971005,SNOMED-CT,Fish (substance),allergy,food,267036007.0,Dyspnea (finding),MODERATE,271807003.0,Eruption of skin (disorder),MILD
938,1968-06-18,NaN,1f8dcaff-1cf9-fac5-a278-8ade5dc2dbf5,1f8dcaff-1cf9-fac5-838a-be81c45c0a2d,442571000124108,SNOMED-CT,Tree nut (substance),allergy,food,267036007.0,Dyspnea (finding),MODERATE,271807003.0,Eruption of skin (disorder),MODERATE
939,1968-06-18,NaN,1f8dcaff-1cf9-fac5-a278-8ade5dc2dbf5,1f8dcaff-1cf9-fac5-838a-be81c45c0a2d,762952008,SNOMED-CT,Peanut (substance),allergy,food,402387002.0,Allergic angioedema (disorder),MODERATE,NaN,NaN,NaN

In [24]:
data3 = data3.rename(columns={

    "7c74cbbf-caf7-3923-add7-b2f9343df1b7": "uuid",
    "environment": "medium_of_contraction",
    "allergy": "type",
    "Unnamed: 11": "severity",
    "Unnamed: 10": "manifestation",
    "Unnamed: 13": "observed_recation",
    "Unnamed: 14": "observed_reaction_effect",
    "Unnamed: 12": "observed_reaction_code",
    "Unnamed: 9": "manifestation_code",
    "7c74cbbf-caf7-3923-924c-85fb53334381": "allergy_record_id",
    "1996-10-03": "allergy_first_recorded",
    "609328004": "allergy_id"
    
    
}).drop(columns=['Unnamed: 1', "SNOMED-CT"])

In [25]:
data3

,allergy_first_recorded,uuid,allergy_record_id,allergy_id,Allergic disposition (finding),type,medium_of_contraction,manifestation_code,manifestation,severity,observed_reaction_code,observed_recation,observed_reaction_effect
0,1996-10-03,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,111088007,Latex (substance),allergy,environment,247472004.0,Wheal (finding),MILD,NaN,NaN,NaN
1,1996-10-03,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,84489001,Mold (organism),allergy,environment,21626009.0,Cutaneous hypersensitivity (disorder),MILD,76067001.0,Sneezing (finding),MILD
2,1996-10-03,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,260147004,House dust mite (organism),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
3,1996-10-03,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,264287008,Animal dander (substance),allergy,environment,878820003.0,Rhinoconjunctivitis (disorder),MODERATE,49727002.0,Cough (finding),MODERATE
4,1996-10-03,7c74cbbf-caf7-3923-add7-b2f9343df1b7,7c74cbbf-caf7-3923-924c-85fb53334381,3718001,Cow's milk (substance),allergy,food,247472004.0,Wheal (finding),MILD,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
935,1968-06-18,1f8dcaff-1cf9-fac5-a278-8ade5dc2dbf5,1f8dcaff-1cf9-fac5-838a-be81c45c0a2d,256277009,Grass pollen (substance),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
936,1968-06-18,1f8dcaff-1cf9-fac5-a278-8ade5dc2dbf5,1f8dcaff-1cf9-fac5-838a-be81c45c0a2d,3718001,Cow's milk (substance),allergy,food,247472004.0,Wheal (finding),MILD,NaN,NaN,NaN
937,1968-06-18,1f8dcaff-1cf9-fac5-a278-8ade5dc2dbf5,1f8dcaff-1cf9-fac5-838a-be81c45c0a2d,735971005,Fish (substance),allergy,food,267036007.0,Dyspnea (finding),MODERATE,271807003.0,Eruption of skin (disorder),MILD
938,1968-06-18,1f8dcaff-1cf9-fac5-a278-8ade5dc2dbf5,1f8dcaff-1cf9-fac5-838a-be81c45c0a2d,442571000124108,Tree nut (substance),allergy,food,267036007.0,Dyspnea (finding),MODERATE,271807003.0,Eruption of skin (disorder),MODERATE
939,1968-06-18,1f8dcaff-1cf9-fac5-a278-8ade5dc2dbf5,1f8dcaff-1cf9-fac5-838a-be81c45c0a2d,762952008,Peanut (substance),allergy,food,402387002.0,Allergic angioedema (disorder),MODERATE,NaN,NaN,NaN

In [34]:
data4 = pd.read_csv('../Datasets/procedures.csv')

In [35]:
data4

,2025-06-13T06:40:38Z,2025-06-13T06:55:38Z,85e5acb8-9ff4-597d-94d2-19704ee2665c,85e5acb8-9ff4-597d-913a-744ae0361d31,http://snomed.info/sct,430193006,Medication reconciliation (procedure),215.70,Unnamed: 8,Unnamed: 9
0,2020-07-19T03:31:16Z,2020-07-19T03:46:16Z,44e5aa82-e51c-af3f-c80a-055fb5f73863,44e5aa82-e51c-af3f-80e4-15b1aca749c4,http://snomed.info/sct,430193006,Medication reconciliation (procedure),215.7,NaN,NaN
1,2020-09-20T03:31:16Z,2020-09-20T03:46:16Z,44e5aa82-e51c-af3f-c80a-055fb5f73863,44e5aa82-e51c-af3f-4e40-3890bb8d5f16,http://snomed.info/sct,430193006,Medication reconciliation (procedure),215.7,NaN,NaN
2,2016-01-04T21:10:05Z,2016-01-04T21:24:03Z,9ec76493-d732-13e5-5cd3-7fa0d2e80ace,9ec76493-d732-13e5-09d8-45a7369d162f,http://snomed.info/sct,103697008,Patient referral for dental care (procedure),431.4,NaN,NaN
3,2016-01-11T21:10:05Z,2016-01-11T21:52:16Z,9ec76493-d732-13e5-5cd3-7fa0d2e80ace,9ec76493-d732-13e5-9c3e-5a08fe98af07,http://snomed.info/sct,34043003,Dental consultation and report (procedure),431.4,103697008.0,Patient referral for dental care (procedure)
4,2016-01-11T21:52:16Z,2016-01-11T22:14:41Z,9ec76493-d732-13e5-5cd3-7fa0d2e80ace,9ec76493-d732-13e5-9c3e-5a08fe98af07,http://snomed.info/sct,225362009,Dental care (regime/therapy),431.4,103697008.0,Patient referral for dental care (procedure)
...,...,...,...,...,...,...,...,...,...,...
177885,2025-06-24T11:02:37Z,2025-06-24T11:33:03Z,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-85a6-887879f5abe8,http://snomed.info/sct,1260009003,Removal of supragingival plaque and calculus f...,431.4,103697008.0,Patient referral for dental care (procedure)
177886,2025-06-24T11:33:03Z,2025-06-24T12:03:35Z,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-85a6-887879f5abe8,http://snomed.info/sct,1260010008,Removal of subgingival plaque and calculus fro...,431.4,103697008.0,Patient referral for dental care (procedure)
177887,2025-06-24T12:03:35Z,2025-06-24T12:33:35Z,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-85a6-887879f5abe8,http://snomed.info/sct,241046008,Dental plain X-ray bitewing (procedure),431.4,NaN,NaN
177888,2025-06-24T12:03:35Z,2025-06-24T12:36:20Z,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-85a6-887879f5abe8,http://snomed.info/sct,274788003,Examination of gingivae (procedure),431.4,103697008.0,Patient referral for dental care (procedure)
177889,2025-06-24T12:36:20Z,2025-06-24T12:51:22Z,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-85a6-887879f5abe8,http://snomed.info/sct,243085009,Oral health education (procedure),431.4,103697008.0,Patient referral for dental care (procedure)

In [36]:
data4[data4['85e5acb8-9ff4-597d-94d2-19704ee2665c'] == "daaf82d6-2984-5da6-ac3c-e2df631879eb"]

,2025-06-13T06:40:38Z,2025-06-13T06:55:38Z,85e5acb8-9ff4-597d-94d2-19704ee2665c,85e5acb8-9ff4-597d-913a-744ae0361d31,http://snomed.info/sct,430193006,Medication reconciliation (procedure),215.70,Unnamed: 8,Unnamed: 9
69,2016-01-10T04:21:36Z,2016-01-10T04:36:36Z,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-9a6c-0cfa8351bd06,http://snomed.info/sct,430193006,Medication reconciliation (procedure),321.65,NaN,NaN
70,2016-01-10T04:21:36Z,2016-01-10T04:52:06Z,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-9a6c-0cfa8351bd06,http://snomed.info/sct,710824005,Assessment of health and social care needs (pr...,431.40,NaN,NaN
71,2016-01-10T04:52:06Z,2016-01-10T05:05:42Z,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-9a6c-0cfa8351bd06,http://snomed.info/sct,171207006,Depression screening (procedure),431.40,NaN,NaN
72,2016-01-10T05:05:42Z,2016-01-10T05:33:20Z,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-9a6c-0cfa8351bd06,http://snomed.info/sct,171207006,Depression screening (procedure),431.40,NaN,NaN
73,2016-01-10T05:33:20Z,2016-01-10T05:45:47Z,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-9a6c-0cfa8351bd06,http://snomed.info/sct,428211000124100,Assessment of substance use (procedure),431.40,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
144,2024-11-24T04:44:32Z,2024-11-24T05:25:58Z,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-218b-dc8496d3f345,http://snomed.info/sct,225362009,Dental care (regime/therapy),431.40,103697008.0,Patient referral for dental care (procedure)
145,2024-11-24T05:25:58Z,2024-11-24T05:40:59Z,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-218b-dc8496d3f345,http://snomed.info/sct,1260009003,Removal of supragingival plaque and calculus f...,431.40,103697008.0,Patient referral for dental care (procedure)
146,2024-11-24T05:40:59Z,2024-11-24T05:59:33Z,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-218b-dc8496d3f345,http://snomed.info/sct,1260010008,Removal of subgingival plaque and calculus fro...,431.40,103697008.0,Patient referral for dental care (procedure)
147,2024-11-24T05:59:33Z,2024-11-24T06:37:40Z,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-218b-dc8496d3f345,http://snomed.info/sct,274788003,Examination of gingivae (procedure),431.40,103697008.0,Patient referral for dental care (procedure)
148,2024-11-24T06:37:40Z,2024-11-24T06:58:05Z,daaf82d6-2984-5da6-ac3c-e2df631879eb,daaf82d6-2984-5da6-218b-dc8496d3f345,http://snomed.info/sct,243085009,Oral health education (procedure),431.40,103697008.0,Patient referral for dental care (procedure)

In [38]:
#Renaming the columns

data4 = data4.rename(columns={

    '85e5acb8-9ff4-597d-94d2-19704ee2665c': 'uuid',
    'Medication reconciliation (procedure)': 'procedure',
    '430193006': 'procedure_id', 
    'Unnamed: 9': 'procedure_reason',
    'Unnamed: 8': 'reasoned_procedure_id'
    
    
}).drop(columns=['http://snomed.info/sct'])

In [39]:
data4

,2025-06-13T06:40:38Z,2025-06-13T06:55:38Z,uuid,85e5acb8-9ff4-597d-913a-744ae0361d31,procedure_id,procedure,215.70,reasoned_procedure_id,procedure_reason
0,2020-07-19T03:31:16Z,2020-07-19T03:46:16Z,44e5aa82-e51c-af3f-c80a-055fb5f73863,44e5aa82-e51c-af3f-80e4-15b1aca749c4,430193006,Medication reconciliation (procedure),215.7,NaN,NaN
1,2020-09-20T03:31:16Z,2020-09-20T03:46:16Z,44e5aa82-e51c-af3f-c80a-055fb5f73863,44e5aa82-e51c-af3f-4e40-3890bb8d5f16,430193006,Medication reconciliation (procedure),215.7,NaN,NaN
2,2016-01-04T21:10:05Z,2016-01-04T21:24:03Z,9ec76493-d732-13e5-5cd3-7fa0d2e80ace,9ec76493-d732-13e5-09d8-45a7369d162f,103697008,Patient referral for dental care (procedure),431.4,NaN,NaN
3,2016-01-11T21:10:05Z,2016-01-11T21:52:16Z,9ec76493-d732-13e5-5cd3-7fa0d2e80ace,9ec76493-d732-13e5-9c3e-5a08fe98af07,34043003,Dental consultation and report (procedure),431.4,103697008.0,Patient referral for dental care (procedure)
4,2016-01-11T21:52:16Z,2016-01-11T22:14:41Z,9ec76493-d732-13e5-5cd3-7fa0d2e80ace,9ec76493-d732-13e5-9c3e-5a08fe98af07,225362009,Dental care (regime/therapy),431.4,103697008.0,Patient referral for dental care (procedure)
...,...,...,...,...,...,...,...,...,...
177885,2025-06-24T11:02:37Z,2025-06-24T11:33:03Z,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-85a6-887879f5abe8,1260009003,Removal of supragingival plaque and calculus f...,431.4,103697008.0,Patient referral for dental care (procedure)
177886,2025-06-24T11:33:03Z,2025-06-24T12:03:35Z,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-85a6-887879f5abe8,1260010008,Removal of subgingival plaque and calculus fro...,431.4,103697008.0,Patient referral for dental care (procedure)
177887,2025-06-24T12:03:35Z,2025-06-24T12:33:35Z,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-85a6-887879f5abe8,241046008,Dental plain X-ray bitewing (procedure),431.4,NaN,NaN
177888,2025-06-24T12:03:35Z,2025-06-24T12:36:20Z,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-85a6-887879f5abe8,274788003,Examination of gingivae (procedure),431.4,103697008.0,Patient referral for dental care (procedure)
177889,2025-06-24T12:36:20Z,2025-06-24T12:51:22Z,197b6d42-0058-1c4e-854b-dea84b26956b,197b6d42-0058-1c4e-85a6-887879f5abe8,243085009,Oral health education (procedure),431.4,103697008.0,Patient referral for dental care (procedure)